server:
  port: 8080 # 포트번호 8080
spring:
  mvc:
    hiddenmethod:      # @DeleteMapping 사용 위해
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grooveo__dev?serverTimezone=Asia/Seoul
    username: grooveouser
    password:
  devtools:
    livereload:        # jps, css 변경 시 새로고침 없이 바로 적용
      enabled: true    # 필요없으면 false
    restart:           # 자동 재시작 사용 여부
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create # DB 테이블 자동생성(엔티티 클래스만 만들면 됨)
    properties:
      hibernate:
        show_sql: true            # 하이버네이트가 DB에 날리는 모든 쿼리(DDL, DML)를 보여준다.
        format_sql: true          # sql 예쁘게 포맷팅
        use_sql_comments: true    # 추가적인 주석 표시